function parseLanguage(code) {
  var match = code.match(/^\s*(.*?)(-(.*))?\s*$/);
  if (!match) return code;
  return {
    language: ISO_639_1_MAP[match[1].toLowerCase()],
    country: ISO_3166_1_MAP[match[3] ? match[3].toUpperCase() : null]
  }
}

var ISO_639_1_MAP = {
  "aa":"Afar",
  "ab":"Abkhazian",
  "af":"Afrikaans",
  "ak":"Akan",
  "am":"Amharic",
  "ar":"Arabic",
  "an":"Aragonese",
  "hy":"Armenian",
  "as":"Assamese",
  "av":"Avaric",
  "ae":"Avestan",
  "ay":"Aymara",
  "az":"Azerbaijani",
  "ba":"Bashkir",
  "bm":"Bambara",
  "eu":"Basque",
  "be":"Belarusian",
  "bn":"Bengali",
  "bh":"Bihari languages",
  "bi":"Bislama",
  "bo":"Tibetan",
  "bs":"Bosnian",
  "br":"Breton",
  "bg":"Bulgarian",
  "my":"Burmese",
  "ca":"Catalan; Valencian",
  "cs":"Czech",
  "ch":"Chamorro",
  "ce":"Chechen",
  "zh":"Chinese",
  "cu":"Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic",
  "cv":"Chuvash",
  "kw":"Cornish",
  "co":"Corsican",
  "cr":"Cree",
  "cy":"Welsh",
  "cs":"Czech",
  "da":"Danish",
  "de":"German",
  "dv":"Divehi; Dhivehi; Maldivian",
  "nl":"Dutch; Flemish",
  "dz":"Dzongkha",
  "el":"Greek, Modern (1453-)",
  "en":"English",
  "eo":"Esperanto",
  "et":"Estonian",
  "eu":"Basque",
  "ee":"Ewe",
  "fo":"Faroese",
  "fa":"Persian",
  "fj":"Fijian",
  "fi":"Finnish",
  "fr":"French",
  "fr":"French",
  "fy":"Western Frisian",
  "ff":"Fulah",
  "ka":"Georgian",
  "de":"German",
  "gd":"Gaelic; Scottish Gaelic",
  "ga":"Irish",
  "gl":"Galician",
  "gv":"Manx",
  "el":"Greek, Modern (1453-)",
  "gn":"Guarani",
  "gu":"Gujarati",
  "ht":"Haitian; Haitian Creole",
  "ha":"Hausa",
  "he":"Hebrew",
  "hz":"Herero",
  "hi":"Hindi",
  "ho":"Hiri Motu",
  "hr":"Croatian",
  "hu":"Hungarian",
  "hy":"Armenian",
  "ig":"Igbo",
  "is":"Icelandic",
  "io":"Ido",
  "ii":"Sichuan Yi; Nuosu",
  "iu":"Inuktitut",
  "ie":"Interlingue; Occidental",
  "ia":"Interlingua (International Auxiliary Language Association)",
  "id":"Indonesian",
  "ik":"Inupiaq",
  "is":"Icelandic",
  "it":"Italian",
  "jv":"Javanese",
  "ja":"Japanese",
  "kl":"Kalaallisut; Greenlandic",
  "kn":"Kannada",
  "ks":"Kashmiri",
  "ka":"Georgian",
  "kr":"Kanuri",
  "kk":"Kazakh",
  "km":"Central Khmer",
  "ki":"Kikuyu; Gikuyu",
  "rw":"Kinyarwanda",
  "ky":"Kirghiz; Kyrgyz",
  "kv":"Komi",
  "kg":"Kongo",
  "ko":"Korean",
  "kj":"Kuanyama; Kwanyama",
  "ku":"Kurdish",
  "lo":"Lao",
  "la":"Latin",
  "lv":"Latvian",
  "li":"Limburgan; Limburger; Limburgish",
  "ln":"Lingala",
  "lt":"Lithuanian",
  "lb":"Luxembourgish; Letzeburgesch",
  "lu":"Luba-Katanga",
  "lg":"Ganda",
  "mk":"Macedonian",
  "mh":"Marshallese",
  "ml":"Malayalam",
  "mi":"Maori",
  "mr":"Marathi",
  "ms":"Malay",
  "mk":"Macedonian",
  "mg":"Malagasy",
  "mt":"Maltese",
  "mn":"Mongolian",
  "mi":"Maori",
  "ms":"Malay",
  "my":"Burmese",
  "na":"Nauru",
  "nv":"Navajo; Navaho",
  "nr":"Ndebele, South; South Ndebele",
  "nd":"Ndebele, North; North Ndebele",
  "ng":"Ndonga",
  "ne":"Nepali",
  "nl":"Dutch; Flemish",
  "nn":"Norwegian Nynorsk; Nynorsk, Norwegian",
  "nb":"Bokmål, Norwegian; Norwegian Bokmål",
  "no":"Norwegian",
  "ny":"Chichewa; Chewa; Nyanja",
  "oc":"Occitan (post 1500)",
  "oj":"Ojibwa",
  "or":"Oriya",
  "om":"Oromo",
  "os":"Ossetian; Ossetic",
  "pa":"Panjabi; Punjabi",
  "fa":"Persian",
  "pi":"Pali",
  "pl":"Polish",
  "pt":"Portuguese",
  "ps":"Pushto; Pashto",
  "qu":"Quechua",
  "rm":"Romansh",
  "ro":"Romanian; Moldavian; Moldovan",
  "ro":"Romanian; Moldavian; Moldovan",
  "rn":"Rundi",
  "ru":"Russian",
  "sg":"Sango",
  "sa":"Sanskrit",
  "si":"Sinhala; Sinhalese",
  "sk":"Slovak",
  "sk":"Slovak",
  "sl":"Slovenian",
  "se":"Northern Sami",
  "sm":"Samoan",
  "sn":"Shona",
  "sd":"Sindhi",
  "so":"Somali",
  "st":"Sotho, Southern",
  "es":"Spanish; Castilian",
  "sq":"Albanian",
  "sc":"Sardinian",
  "sr":"Serbian",
  "ss":"Swati",
  "su":"Sundanese",
  "sw":"Swahili",
  "sv":"Swedish",
  "ty":"Tahitian",
  "ta":"Tamil",
  "tt":"Tatar",
  "te":"Telugu",
  "tg":"Tajik",
  "tl":"Tagalog",
  "th":"Thai",
  "bo":"Tibetan",
  "ti":"Tigrinya",
  "to":"Tonga (Tonga Islands)",
  "tn":"Tswana",
  "ts":"Tsonga",
  "tk":"Turkmen",
  "tr":"Turkish",
  "tw":"Twi",
  "ug":"Uighur; Uyghur",
  "uk":"Ukrainian",
  "ur":"Urdu",
  "uz":"Uzbek",
  "ve":"Venda",
  "vi":"Vietnamese",
  "vo":"Volapük",
  "cy":"Welsh",
  "wa":"Walloon",
  "wo":"Wolof",
  "xh":"Xhosa",
  "yi":"Yiddish",
  "yo":"Yoruba",
  "za":"Zhuang; Chuang",
  "zh":"Chinese",
  "zu":"Zulu"
}

var ISO_3166_1_MAP = {
  "AF":"AFGHANISTAN",
  "AX":"ÅLAND ISLANDS",
  "AL":"ALBANIA",
  "DZ":"ALGERIA",
  "AS":"AMERICAN SAMOA",
  "AD":"ANDORRA",
  "AO":"ANGOLA",
  "AI":"ANGUILLA",
  "AQ":"ANTARCTICA",
  "AG":"ANTIGUA AND BARBUDA",
  "AR":"ARGENTINA",
  "AM":"ARMENIA",
  "AW":"ARUBA",
  "AU":"AUSTRALIA",
  "AT":"AUSTRIA",
  "AZ":"AZERBAIJAN",
  "BS":"BAHAMAS",
  "BH":"BAHRAIN",
  "BD":"BANGLADESH",
  "BB":"BARBADOS",
  "BY":"BELARUS",
  "BE":"BELGIUM",
  "BZ":"BELIZE",
  "BJ":"BENIN",
  "BM":"BERMUDA",
  "BT":"BHUTAN",
  "BO":"BOLIVIA, PLURINATIONAL STATE OF",
  "BA":"BOSNIA AND HERZEGOVINA",
  "BW":"BOTSWANA",
  "BV":"BOUVET ISLAND",
  "BR":"BRAZIL",
  "IO":"BRITISH INDIAN OCEAN TERRITORY",
  "BN":"BRUNEI DARUSSALAM",
  "BG":"BULGARIA",
  "BF":"BURKINA FASO",
  "BI":"BURUNDI",
  "KH":"CAMBODIA",
  "CM":"CAMEROON",
  "CA":"CANADA",
  "CV":"CAPE VERDE",
  "KY":"CAYMAN ISLANDS",
  "CF":"CENTRAL AFRICAN REPUBLIC",
  "TD":"CHAD",
  "CL":"CHILE",
  "CN":"CHINA",
  "CX":"CHRISTMAS ISLAND",
  "CC":"COCOS (KEELING) ISLANDS",
  "CO":"COLOMBIA",
  "KM":"COMOROS",
  "CG":"CONGO",
  "CD":"CONGO, THE DEMOCRATIC REPUBLIC OF THE",
  "CK":"COOK ISLANDS",
  "CR":"COSTA RICA",
  "CI":"CÔTE D'IVOIRE",
  "HR":"CROATIA",
  "CU":"CUBA",
  "CY":"CYPRUS",
  "CZ":"CZECH REPUBLIC",
  "DK":"DENMARK",
  "DJ":"DJIBOUTI",
  "DM":"DOMINICA",
  "DO":"DOMINICAN REPUBLIC",
  "EC":"ECUADOR",
  "EG":"EGYPT",
  "SV":"EL SALVADOR",
  "GQ":"EQUATORIAL GUINEA",
  "ER":"ERITREA",
  "EE":"ESTONIA",
  "ET":"ETHIOPIA",
  "FK":"FALKLAND ISLANDS (MALVINAS)",
  "FO":"FAROE ISLANDS",
  "FJ":"FIJI",
  "FI":"FINLAND",
  "FR":"FRANCE",
  "GF":"FRENCH GUIANA",
  "PF":"FRENCH POLYNESIA",
  "TF":"FRENCH SOUTHERN TERRITORIES",
  "GA":"GABON",
  "GM":"GAMBIA",
  "GE":"GEORGIA",
  "DE":"GERMANY",
  "GH":"GHANA",
  "GI":"GIBRALTAR",
  "GR":"GREECE",
  "GL":"GREENLAND",
  "GD":"GRENADA",
  "GP":"GUADELOUPE",
  "GU":"GUAM",
  "GT":"GUATEMALA",
  "GG":"GUERNSEY",
  "GN":"GUINEA",
  "GW":"GUINEA-BISSAU",
  "GY":"GUYANA",
  "HT":"HAITI",
  "HM":"HEARD ISLAND AND MCDONALD ISLANDS",
  "VA":"HOLY SEE (VATICAN CITY STATE)",
  "HN":"HONDURAS",
  "HK":"HONG KONG",
  "HU":"HUNGARY",
  "IS":"ICELAND",
  "IN":"INDIA",
  "ID":"INDONESIA",
  "IR":"IRAN, ISLAMIC REPUBLIC OF",
  "IQ":"IRAQ",
  "IE":"IRELAND",
  "IM":"ISLE OF MAN",
  "IL":"ISRAEL",
  "IT":"ITALY",
  "JM":"JAMAICA",
  "JP":"JAPAN",
  "JE":"JERSEY",
  "JO":"JORDAN",
  "KZ":"KAZAKHSTAN",
  "KE":"KENYA",
  "KI":"KIRIBATI",
  "KP":"KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF",
  "KR":"KOREA, REPUBLIC OF",
  "KW":"KUWAIT",
  "KG":"KYRGYZSTAN",
  "LA":"LAO PEOPLE'S DEMOCRATIC REPUBLIC",
  "LV":"LATVIA",
  "LB":"LEBANON",
  "LS":"LESOTHO",
  "LR":"LIBERIA",
  "LY":"LIBYAN ARAB JAMAHIRIYA",
  "LI":"LIECHTENSTEIN",
  "LT":"LITHUANIA",
  "LU":"LUXEMBOURG",
  "MO":"MACAO",
  "MK":"MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF",
  "MG":"MADAGASCAR",
  "MW":"MALAWI",
  "MY":"MALAYSIA",
  "MV":"MALDIVES",
  "ML":"MALI",
  "MT":"MALTA",
  "MH":"MARSHALL ISLANDS",
  "MQ":"MARTINIQUE",
  "MR":"MAURITANIA",
  "MU":"MAURITIUS",
  "YT":"MAYOTTE",
  "MX":"MEXICO",
  "FM":"MICRONESIA, FEDERATED STATES OF",
  "MD":"MOLDOVA, REPUBLIC OF",
  "MC":"MONACO",
  "MN":"MONGOLIA",
  "ME":"MONTENEGRO",
  "MS":"MONTSERRAT",
  "MA":"MOROCCO",
  "MZ":"MOZAMBIQUE",
  "MM":"MYANMAR",
  "NA":"NAMIBIA",
  "NR":"NAURU",
  "NP":"NEPAL",
  "NL":"NETHERLANDS",
  "AN":"NETHERLANDS ANTILLES",
  "NC":"NEW CALEDONIA",
  "NZ":"NEW ZEALAND",
  "NI":"NICARAGUA",
  "NE":"NIGER",
  "NG":"NIGERIA",
  "NU":"NIUE",
  "NF":"NORFOLK ISLAND",
  "MP":"NORTHERN MARIANA ISLANDS",
  "NO":"NORWAY",
  "OM":"OMAN",
  "PK":"PAKISTAN",
  "PW":"PALAU",
  "PS":"PALESTINIAN TERRITORY, OCCUPIED",
  "PA":"PANAMA",
  "PG":"PAPUA NEW GUINEA",
  "PY":"PARAGUAY",
  "PE":"PERU",
  "PH":"PHILIPPINES",
  "PN":"PITCAIRN",
  "PL":"POLAND",
  "PT":"PORTUGAL",
  "PR":"PUERTO RICO",
  "QA":"QATAR",
  "RE":"RÉUNION",
  "RO":"ROMANIA",
  "RU":"RUSSIAN FEDERATION",
  "RW":"RWANDA",
  "BL":"SAINT BARTHÉLEMY",
  "SH":"SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA",
  "KN":"SAINT KITTS AND NEVIS",
  "LC":"SAINT LUCIA",
  "MF":"SAINT MARTIN",
  "PM":"SAINT PIERRE AND MIQUELON",
  "VC":"SAINT VINCENT AND THE GRENADINES",
  "WS":"SAMOA",
  "SM":"SAN MARINO",
  "ST":"SAO TOME AND PRINCIPE",
  "SA":"SAUDI ARABIA",
  "SN":"SENEGAL",
  "RS":"SERBIA",
  "SC":"SEYCHELLES",
  "SL":"SIERRA LEONE",
  "SG":"SINGAPORE",
  "SK":"SLOVAKIA",
  "SI":"SLOVENIA",
  "SB":"SOLOMON ISLANDS",
  "SO":"SOMALIA",
  "ZA":"SOUTH AFRICA",
  "GS":"SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
  "ES":"SPAIN",
  "LK":"SRI LANKA",
  "SD":"SUDAN",
  "SR":"SURINAME",
  "SJ":"SVALBARD AND JAN MAYEN",
  "SZ":"SWAZILAND",
  "SE":"SWEDEN",
  "CH":"SWITZERLAND",
  "SY":"SYRIAN ARAB REPUBLIC",
  "TW":"TAIWAN, PROVINCE OF CHINA",
  "TJ":"TAJIKISTAN",
  "TZ":"TANZANIA, UNITED REPUBLIC OF",
  "TH":"THAILAND",
  "TL":"TIMOR-LESTE",
  "TG":"TOGO",
  "TK":"TOKELAU",
  "TO":"TONGA",
  "TT":"TRINIDAD AND TOBAGO",
  "TN":"TUNISIA",
  "TR":"TURKEY",
  "TM":"TURKMENISTAN",
  "TC":"TURKS AND CAICOS ISLANDS",
  "TV":"TUVALU",
  "UG":"UGANDA",
  "UA":"UKRAINE",
  "AE":"UNITED ARAB EMIRATES",
  "GB":"UNITED KINGDOM",
  "US":"UNITED STATES",
  "UM":"UNITED STATES MINOR OUTLYING ISLANDS",
  "UY":"URUGUAY",
  "UZ":"UZBEKISTAN",
  "VU":"VANUATU",
  "VE":"VENEZUELA, BOLIVARIAN REPUBLIC OF",
  "VN":"VIET NAM",
  "VG":"VIRGIN ISLANDS, BRITISH",
  "VI":"VIRGIN ISLANDS, U.S.",
  "WF":"WALLIS AND FUTUNA",
  "EH":"WESTERN SAHARA",
  "YE":"YEMEN",
  "ZM":"ZAMBIA",
  "ZW":"ZIMBABWE"
}